language: python
python:
#  - "3.8"
  - "3.9"
#  - "3.9-dev"  # 3.9 development branch
#  - "nightly"  # nightly build
env:
  - NOTESDIR=./__testing__/notesdir
# before install
before_install:
  - python --version
  - sudo apt install gnupg
  - pip install -U pip
# command to install dependencies
install:
  - python -m venv venv
  - . venv/bin/activate
  - pip install wheel
  - pip install pytest-cov pytest
  - pip install python-gnupg toml
# command to run tests
script:
  - pip freeze
  - python setup.py bdist_wheel
  - pip install -e . 
  - pip freeze
  - mkdir -p __testing__/notesdir
  - gpg --import gpgkeys/key-B44A9055.asc  gpgkeys/key-BB3EB284.asc
  - gpg --import-ownertrust < gpgkeys/9055.ownertrust
  - gpg --import-ownertrust < gpgkeys/b284.ownertrust
  - pytest
#  - pytest --cov-config=.coveragerc --cov=pynoteslib  tests/
# after sucessful tests
after_success: coverage report
